import json
from roborock import *
from roborock.version_a01_apis.roborock_mqtt_client_a01 import RoborockMqttClientA01
from roborock.version_1_apis.roborock_mqtt_client_v1 import RoborockMqttClientV1
from roborock.web_api import RoborockApiClient
